CREATE TABLE IF NOT EXISTS usuarios ( id INT(11) AUTO_INCREMENT, usuario VARCHAR(20), senha VARCHAR(128), PRIMARY KEY(id) );
CREATE TABLE IF NOT EXISTS sessoes ( id INT(11) AUTO_INCREMENT, usuario VARCHAR(20), senha VARCHAR(128), sessao VARCHAR(128), PRIMARY KEY(id) );
